- name: Create overrides folder for locksmithd
  file:
    path: /etc/systemd/system/locksmithd.service.d
    state: directory
    owner: root
    group: root
    mode: 0755
- name: Configure locksmithd
  template:
    dest: /etc/systemd/system/locksmithd.service.d/locksmithd.conf
    src: locksmithd.conf.j2
    owner: root
    group: root
    mode: 0644
  register: locksmithd_config
- name: Reloading systemd
  command: systemctl daemon-reload
  when: locksmithd_config.changed
- name: Restart locksmithd
  service: name=locksmithd state=restarted enabled=yes
  when: locksmithd_config.changed
- name: Start locksmithd
  service: name=locksmithd state=started enabled=yes
- name: Stop update-engine temporarly
  service: name=update-engine state=stopped enabled=yes
