- name: Install LVM
  yum:
    name: lvm2

- name: Comnfigure lvm.conf
  command: "{{ item }}"
  with_items:
  - sed -i 's/^[[:space:]]\+thin_pool_autoextend_threshold.*/\tthin_pool_autoextend_threshold = 80/' /etc/lvm/lvm.conf
  - sed -i 's/^[[:space:]]\+thin_pool_autoextend_percent.*/\tthin_pool_autoextend_percent = 20/' /etc/lvm/lvm.conf
  - systemctl restart lvm2-monitor.service

- name: Configuring LVM to use /dev/vdb
  command: "{{ item }}"
  with_items:
  - parted /dev/vdb mklabel gpt
  - parted /dev/vdb mkpart gentoo ext2 1 -- -1
  - parted /dev/vdb set 1 lvm on
  - pvcreate /dev/vdb1
  - vgcreate vg /dev/vdb1

