- name: Generate node Kubernetes certificates
  command: env CERT_ORG="system:masters" ./tls/generate_cert.sh kubernetes client kube-admin
  args:
    creates: tls/kubernetes/kube-admin.pem
- name: Generating kubeconfig
  template:
    src: kubeconfig.j2
    dest: ./kubeconfig
    mode: 0600
- name: Waiting for API server to become ready
  wait_for:
    host: "{{ hostvars[groups['masters'][0]]['public_ip'] }}"
    port: 8443
- name: Clear Kubernetes configuration directory
  file:
    dest: ./cluster_config
    state: absent
- name: Prepare Kubernetes configuration directory
  file:
    dest: ./cluster_config
    state: directory
- name: Copy configuration files
  copy:
    src: "{{ item }}"
    dest: "./cluster_config/{{ item | basename }}"
  with_fileglob:
  - '*.yaml'
- name: Initialize templated configuration files
  template:
    src: "{{ item }}"
    dest: "./cluster_config/{{ item | basename | regex_replace('\\.j2$','') }}"
  with_fileglob:
  - '../templates/*.yaml.j2'
- name: Create required pod security policies
  command: kubectl --kubeconfig kubeconfig apply -f ./cluster_config/podsecuritypolicy.yaml
- name: Install cert-manager
  command: kubectl --kubeconfig kubeconfig apply -f ./cluster_config/cert-manager.yaml
- name: wait 10 seconds for CRDs to become available for use
  wait_for: timeout=10
  delegate_to: localhost
- name: Apply all configuration files
  command: kubectl --kubeconfig kubeconfig apply -f ./cluster_config
