# Deployment vars
kubernetes_namespace: monitoring

# Ingress
ingress_host: prometheus.uninett.no

# Common
configmap_reloader_image: jimmidyson/configmap-reload:v0.2.2

# Prometheus
prometheus_server_image: prom/prometheus:v2.6.1
prometheus_storage_class_name: beta
prometheus_storage_class_size: 75Gi

# Alertmanager
alertmanager_image: prom/alertmanager:v0.16.0
alertmanager_storage_class_name: beta
alertmanager_storage_class_size: 5Gi

# Alertmanager Zabbix integration
# Webhook
# Source: https://scm.uninett.no/asm/alertmanager-zabbix-webhook
alertmanager_zabbix_webhook_image: registry.uninett.no/public/alertmanager-zabbix-webhook:latest
alertmanager_zabbix_webhook_listen_port: 8080
alertmanager_zabbix_webhook_queue_capacity: 500
zabbix_server_host: zabbix-backend.uninett.no
zabbix_server_port: 10051
zabbix_host_annotation: zabbix
zabbix_key_prefix: prometheus

# Provisioner
# Source: https://scm.uninett.no/asm/alertmanager-zabbix-provisioner
alertmanager-zabbix_provisioner_image: registry.uninett.no/public/alertmanager-zabbix-provisioner:latest
